CLASS zcl_rd_hello_world DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES: IF_OO_ADT_CLASSRUN.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_rd_hello_world IMPLEMENTATION.

method:IF_OO_ADT_CLASSRUN~main.

out->write( 'Hello World' ).
ENDMETHOD.
ENDCLASS.
